services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    # network_mode: host
    environment:
      - TZ=America/New_York
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - ./data/mosquitto:/mosquitto/data
      - ./log/mosquitto:/mosquitto/log
    ports:
      - 1883:1883
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
    ports:
      - 1880:1880
    volumes:
      - ./data/node-red:/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana

  influxdb:
    image: influxdb:1.11.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ./config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/influxdb:/var/lib/influxdb
